### PR TITLE
Milestone-7-Portfolio-Accessibility

### PR DESCRIPTION
**Pull request by eroiyo**
We will start looking for accessibility issues in the project.

### CODE REVIEW

**Comment by Metsanpeitto** [comment]
This is a list of the points that would need improvement when fitting the page for accessibility rules:
- Title : 
     - The document title should be descriptive. For example Arturo Ortega Portfolio.
     - There should be only one h1 tag element.
 - Image text alternatives  :  
     - Some of the images needed and alternative text describing the content of the image. 
 - Resize :
     For example, some elements in the page, for example, the h1 tag and navbar elements should keep their aspect ratio when responsiveness is applied. Change the values that use 'vw' for '%' in padding and margins, and use pixels for font sizes.

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
## Hi @eroiyo, 

Good job so far! your portfolio is looking dope already, However, there are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️

- [ ] Use this [Link](https://www.aditus.io/) to check if the contrast ratio of your project is enough currently your buttons have issues kindly fix that
- [ ] I suggest that you link the navbar links with related sections because for now, links don't take you anywhere and you can make the logo take you to the main section


### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by eroiyo** [comment]
Thanks you! i will do these changes 👍

**Comment by eroiyo** [comment]
Changes done!, the font size of the mail is now bigger, and the navbar now have functions, but the buttons are part of the design, i have to stick to the design

**Review by Shaher-11 — APPROVED** [review]
Hello @eroiyo ,

# Congratulations! 🎉 
#### Your project is approved!  There is nothing else to say other than... it's time to merge it :muscle: :muscle: 

## Optional Suggestions 💡
_The following points are optional to implement however they're highly recommended!_:blush:

- Kindly align the mail icon with the nav items.
- the send button needs to be a bit smaller.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

**Comment by eroiyo** [comment]
Thanks you, i will do these changes

**Pull request merged**
