### PR TITLE
Milestone 8: Menu events

### PR DESCRIPTION
**Pull request by eroiyo**
Add the phone menu 📱

-the menu can be accessed any place of the screen.
-the menu will display all the navigation options of the pages.
-have a unique background and take all the screen

### CODE REVIEW

**Review by vichuge — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

mario_ladders

## Good points 👍 
- No Linters error ✔️

## Aspects to improve ♻️

- [ ] When I scroll down the page, the navbar is snuggled to the top, like this:
image
- I kindly invite you to fix this bug, this would help to see good the burger icon and doesn't having the name cut off.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by eroiyo** [comment]
Hello Reviewer! i accidentally asked for a request for "Portfolio: details popup window", sorry it was intended for "Portfolio: mobile menu" not was my intention

**Review by Temmarie — COMMENTED** [review]
## Status: Invalid ❗ 

### Hi @eroiyo  👋🏾 , 

 **While you made a great effort in this project, unfortunately, I cannot proceed to review your code.**

### Invalid Code Review Request

I have to mark this submission as invalid because you have submitted this project for review under the wrong project in your dashboard. 

#### Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

#### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by eroiyo** [comment]
> ## Status: Invalid ❗
> ### Hi @eroiyo 👋🏾 ,
> **While you made a great effort in this project, unfortunately, I cannot proceed to review your code.**
> 
> ### Invalid Code Review Request
> I have to mark this submission as invalid because you have submitted this project for review under the wrong project in your dashboard.
> 
> #### Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> #### Cheers and Happy coding!👏👏👏
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._



> ## Status: Invalid ❗
> ### Hi @eroiyo 👋🏾 ,
> **While you made a great effort in this project, unfortunately, I cannot proceed to review your code.**
> 
> ### Invalid Code Review Request
> I have to mark this submission as invalid because you have submitted this project for review under the wrong project in your dashboard.
> 
> #### Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> #### Cheers and Happy coding!👏👏👏
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Thanks, sorry for the 

> ## Status: Invalid ❗
> ### Hi @eroiyo 👋🏾 ,
> **While you made a great effort in this project, unfortunately, I cannot proceed to review your code.**
> 
> ### Invalid Code Review Request
> I have to mark this submission as invalid because you have submitted this project for review under the wrong project in your dashboard.
> 
> #### Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> #### Cheers and Happy coding!👏👏👏
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Thanks!, sorry for the incovenience

**Review by Dipeshtwis — APPROVED** [review]
# Status: Approved ✔️

## Hi @eroiyo, 

Good job on implementing the suggested changes. Well Done.
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

**You may close this Pull Request and merge the changes**

  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
_**Dipesh Kumar**_

--------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
